# Generated by Django 6.1 on 2026-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Modern Institute of Technology', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Learn. Celebrate. Grow.', max_length=200)),
                ('history', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('courses', models.TextField(blank=True, default='')),
                ('branches', models.TextField(blank=True, default='')),
                ('facilities', models.TextField(blank=True, default='')),
                ('principal_name', models.CharField(blank=True, default='', max_length=200)),
                ('principal_message', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('established_year', models.CharField(blank=True, default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='college/')),
            ],
            options={
                'verbose_name': 'College Information',
                'verbose_name_plural': 'College Information',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('College', 'College'), ('Campus', 'Campus'), ('Classrooms', 'Classrooms'), ('Laboratories', 'Laboratories'), ('Fresher Party', 'Fresher Party'), ('Events', 'Events'), ('Students', 'Students'), ('Faculty', 'Faculty')], db_index=True, max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Optional external image URL used if no image file is uploaded.', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated faculty number, e.g. FAC001', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('branch', models.CharField(db_index=True, max_length=40)),
                ('designation', models.CharField(blank=True, default='Faculty', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faculty_number'],
                'indexes': [models.Index(fields=['name'], name='party_facul_name_545469_idx'), models.Index(fields=['branch'], name='party_facul_branch_184889_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique registration number, e.g. FR20260001', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('marks', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage marks obtained (e.g. 86.50)', max_digits=5)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics & Communication'), ('Mechanical', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('Management', 'Business Management'), ('Mathematics', 'Mathematics'), ('Other', 'Other')], db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['name'], name='party_stude_name_51f8e4_idx'), models.Index(fields=['branch'], name='party_stude_branch_317359_idx'), models.Index(fields=['registration_number'], name='party_stude_registr_73cd62_idx')],
            },
        ),
    ]
